import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveEditScope,isolateEditTargets,runScopedEdit,applyDirectorOps} from '../director-edit.mjs';
import {chooseGlobalShot} from '../global-director.mjs';
import {compileTechnique} from '../studio-techniques.mjs';
const video=(id,from,shotId='a')=>({id,type:'video',trackId:'picture',from,durationInFrames:30,label:'晓美焰 '+id,mediaId:'ep',src:'/mad-media/ep/edit-preview-v2.mp4',sourceStart:20,sourceEnd:44,sourceFps:24,sourceDuration:2400,speed:1,volume:-60,mad:{shotId},transform:{width:960,height:540}});
function fixture(){const project={id:'mad-main',duration:3,metadata:{fps:30,width:960,height:540},timeline:{tracks:[{id:'picture'},{id:'music'},{id:'source-audio'}],items:[video('a',0),video('b',30),video('c',60),{id:'music',type:'audio',trackId:'music',mediaId:'song',from:0,durationInFrames:90}],keyframes:[],transitions:[]}};const shots=['a','b','c'].map((id,n)=>({id,sourceId:'ep',description:'晓美焰 '+id,directorRole:'resolve',directorFit:3,start:100*n/24,end:(100*n+80)/24,startFrame:100*n,endFrame:100*n+80,safeRanges:[{startFrame:100*n+5,endFrame:100*n+75}],semantic:{emotion:'坚定'},cues:[]}));return {project,library:{sources:[{id:'ep',duration:100,fps:24,episode:1}],music:[{id:'song',name:'音乐'}]},resources:{shots,motion:Object.fromEntries(shots.map(s=>[s.id,{ranges:[{startFrame:s.startFrame+5,endFrame:s.startFrame+75,delta:Array(70).fill(2),brightness:Array(70).fill(100),detail:Array(70).fill(20)}]}]))}};}
test('noncontiguous selection and I/O intersection never fill unselected gaps',()=>{const {project}=fixture();const s=resolveEditScope(project,{mode:'intersection',selectedIds:['a','c'],in:15,out:75});assert.deepEqual(s.intervals,[[15,30],[60,75]]);const isolated=isolateEditTargets(project,s);assert.equal(isolated.ids.length,2);assert.deepEqual(isolated.project.timeline.items.find(i=>i.id==='b'),project.timeline.items[1]);const a=isolated.project.timeline.items.filter(i=>i.type==='video'&&i.from<30);assert.equal(a[0].sourceStart,20);assert.equal(a[0].durationInFrames,15);assert.equal(a[1].sourceStart,32);assert.equal(a[1].from,15);assert.equal(a[1].durationInFrames,15);});
test('empty selections, reversed ranges and locked partial items cannot expand scope',()=>{const {project}=fixture();assert.throws(()=>resolveEditScope(project,{mode:'selection',selectedIds:[]}),/尚未选中/);assert.throws(()=>resolveEditScope(project,{mode:'range',in:50,out:20}),/有效帧区间/);project.timeline.tracks[0].locked=true;assert.equal(isolateEditTargets(project,resolveEditScope(project,{mode:'range',in:5,out:15})).ids.length,0);});
test('scoped replacement preserves every other item and consumes actual updated neighbors',async()=>{const f=fixture(),before=structuredClone(f.project),inputs=[];const result=await runScopedEdit({...f,body:{scope:{mode:'selection',selectedIds:['b']},goal:'晓美焰',prompt:'更坚定',audioMode:'preserve',allowed:{shots:true}},chooseShot:opts=>chooseGlobalShot(opts,{recall:async()=>({scope:{eligible:3,episodes:[1]},candidates:f.resources.shots.map(s=>({...s,recallScore:1})),lanes:[],ms:1}),prepare:async()=>{},evidence:async items=>items.map(()=>({url:'test.jpg',data:'test-image'})),events:async()=>({events:[]})}),ask:async input=>{inputs.push(input);return{ms:2,result:{model:'test-only',answers:Object.fromEntries(Object.entries(input.questions).map(([k,q])=>[k,q.type==='score'?{score:input.winnow&&input.state.candidates.find(c=>c.id===k)?.visual==='晓美焰 a'?0:3}:{choice:'c1'}]))}};}});assert.deepEqual(result.project.timeline.items.filter(i=>i.id!=='b'),before.timeline.items.filter(i=>i.id!=='b'));assert.notEqual(result.project.timeline.items.find(i=>i.id==='b').mad.shotId,'a');assert.deepEqual(inputs.find(i=>i.winnow?.images).state.previous,['晓美焰 a']);assert.deepEqual(f.project,before);});
test('cancelled edit cannot call model or change source project',async()=>{const f=fixture();await assert.rejects(runScopedEdit({...f,body:{scope:{mode:'all'},allowed:{}},ask:()=>{throw Error('must not run');},cancelled:()=>true}),/已取消/);});
test('source mute preserves music and out-of-scope audio',async()=>{const f=fixture();f.project.timeline.items.push({id:'sfx-b',type:'audio',trackId:'source-audio',from:33,durationInFrames:10},{id:'outside-sfx',type:'audio',trackId:'source-audio',from:65,durationInFrames:10});const result=await runScopedEdit({...f,body:{scope:{mode:'selection',selectedIds:['b']},audioMode:'mute',allowed:{shots:false}},ask:()=>{throw Error('no decision needed');}});assert.ok(!result.project.timeline.items.some(i=>i.id==='sfx-b'));assert.deepEqual(result.project.timeline.items.find(i=>i.id==='outside-sfx'),f.project.timeline.items.find(i=>i.id==='outside-sfx'));assert.deepEqual(result.project.timeline.items.find(i=>i.id==='music'),f.project.timeline.items.find(i=>i.id==='music'));});
test('compiler pulse operations produce native keyframes and return to rest',()=>{const {project}=fixture();const ops=compileTechnique({technique:'impact',requestId:'pulse',occurrenceId:'b',localFrame:0,durationInFrames:8,scale:1.13,rgbAmount:.004},project).ops;const next=applyDirectorOps(project,ops);const width=next.timeline.keyframes.find(k=>k.itemId==='b').properties.find(p=>p.property==='width').keyframes;assert.equal(width[0].value,960);assert.equal(width.at(-1).value,960);assert.ok(width.some(f=>f.value>1000));assert.deepEqual(next.timeline.items.find(i=>i.id==='a'),project.timeline.items[0]);});
test('separated voice cannot silently fall back to the original mixture',async()=>{const f=fixture();await assert.rejects(runScopedEdit({...f,body:{scope:{mode:'all'},audioMode:'voice'},ask:()=>{throw Error('must not run');}}),/人声分离尚未就绪/);});
test('applied transition retains its rendering track',()=>{const {project}=fixture();const p=applyDirectorOps(project,[{op:'addTransition',leftClipId:'a',rightClipId:'b',durationInFrames:6,presentation:'dipToColorDissolve',type:'crossfade',alignment:.5,timing:'linear'}]);assert.equal(p.timeline.transitions[0].trackId,'picture');});
