import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile,copyFile,mkdtemp} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {expectedCatalogEpisodes,readyCatalogSources} from '../apps/backend/release-catalog.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const ffmpegAvailable=spawnSync('ffmpeg',['-version'],{windowsHide:true}).status===0;
test('one-source bootstrap publishes vectors, creates CPU edit proxy, and retains good index on partial input',{skip:!ffmpegAvailable},async()=>{
 await mkdir(path.join(root,'.sync'),{recursive:true});const work=await mkdtemp(path.join(root,'.sync/bootstrap-smoke-'));
 const catalog=path.join(work,'.local/catalog-v2'),dir=path.join(catalog,'episode-01'),media=path.join(work,'.local/media/source1');
 await Promise.all([mkdir(dir,{recursive:true}),mkdir(media,{recursive:true}),mkdir(path.join(work,'scripts'),{recursive:true})]);
 const json=(p,v)=>writeFile(p,JSON.stringify(v));
 const exec=(command,args)=>{const r=spawnSync(command,args,{cwd:work,encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(r.status,0,r.stderr||r.error?.message);return r.stdout;};
 await copyFile(path.join(root,'apps/backend/release-catalog.mjs'),path.join(work,'release-catalog.mjs'));
 await copyFile(path.join(root,'apps/backend/repeated-sequences.mjs'),path.join(work,'repeated-sequences.mjs'));
 for(const name of ['build-embeddings.mjs','prepare-editor-proxies.mjs'])await copyFile(path.join(root,'apps/backend/scripts',name),path.join(work,'scripts',name));
 await writeFile(path.join(work,'catalog.mjs'),`import {readFile,writeFile,mkdir} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';export const root=fileURLToPath(new URL('./',import.meta.url)),catalogRoot=path.join(root,'.local/catalog-v2');export async function atomicJson(file,data){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,JSON.stringify(data));}export async function preparedSources(){return [JSON.parse(await readFile(path.join(catalogRoot,'episode-01/source.json'),'utf8'))];}export async function execFile(){throw Error('unexpected');}`);
 await writeFile(path.join(work,'gemini.mjs'),`export async function configuration(){return {GEMINI_EMBEDDING_MODEL:'mock-vector'};}export async function embedBatch(parts){return {vectors:parts.map(()=>Array.from({length:768},(_,i)=>i===0?1:0))};}`);
 exec('ffmpeg',['-v','error','-y','-f','lavfi','-i','testsrc2=size=160x90:rate=24','-t','1','-c:v','libx264',path.join(media,'preview.mp4')]);
 exec('ffmpeg',['-v','error','-y','-i',path.join(media,'preview.mp4'),'-frames:v','1',path.join(media,'thumb.jpg')]);
 const source={id:'source1',episode:1,dir:media,duration:1,sourceSha256:'synthetic',thumbVersion:2,semanticStatus:'complete',shots:[{id:'shot1',sourceId:'source1',start:0,end:1,thumb:'thumb.jpg',document:'synthetic clip',semanticStatus:'complete',semantic:{}}]};
 await json(path.join(catalog,'input-manifest.json'),{videos:[{episode:1}]});await json(path.join(catalog,'repeated-sequences.json'),{sources:{}});
 await json(path.join(dir,'source.json'),source);await json(path.join(dir,'enriched.json'),source);
 assert.deepEqual(await expectedCatalogEpisodes(catalog),[1]);assert.equal((await readyCatalogSources(catalog)).length,1);
 exec(process.execPath,['scripts/prepare-editor-proxies.mjs','--catalog','--cpu']);
 const proxy=JSON.parse(exec('ffprobe',['-v','error','-select_streams','v:0','-show_entries','stream=nb_frames,avg_frame_rate','-of','json',path.join(media,'edit-preview-v2.mp4')]));
 assert.equal(Number(proxy.streams[0].nb_frames),24);assert.equal(proxy.streams[0].avg_frame_rate,'24/1');
 exec(process.execPath,['scripts/build-embeddings.mjs']);
 const original=await readFile(path.join(catalog,'vector-index.json'),'utf8'),index=JSON.parse(original);
 assert.equal(index.sourceCount,1);assert.equal(index.entries.length,1);assert.equal((await readFile(path.join(catalog,index.vectorFile))).length,768*4);
 const second=path.join(catalog,'episode-02');await mkdir(second);
 await json(path.join(catalog,'input-manifest.json'),{videos:[{episode:1},{episode:2}]});
 await json(path.join(second,'enriched.json'),{...source,id:'source2',episode:2,semanticStatus:'partial'});
 const incomplete=spawnSync(process.execPath,['scripts/build-embeddings.mjs'],{cwd:work,encoding:'utf8',windowsHide:true});
 assert.equal(incomplete.status,1);assert.equal(await readFile(path.join(catalog,'vector-index.json'),'utf8'),original);
 await assert.rejects(readyCatalogSources(catalog));
});
